const tweets = [
  {
    id: 't0',
    user: {
      id: 'u1',
      username: 'VadimNotJustDev',
      name: 'Vadim',
      image: 'https://github.com/silvaneimartins.png',
    },
    createdAt: '2020-08-27T12:00:00.000Z',
    content: 'Can you please check if the Subscribe button on Youtube works?',
    image: 'https://th.bing.com/th/id/OIG.USvQ6IppK.OGxmi5_yIA?pid=ImgGn',
    numberOfComments: 123,
    numberOfRetweets: 11,
    numberOfLikes: 10,
  },
  {
    id: '111111111',
    createdAt: '2023-04-28T08:30:00.000Z',
    user: {
      id: '123456789',
      name: 'Jeff B',
      username: 'bezos',
      image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/jeff.jpeg',
    },
    content: 'Just had a great workout at the gym! 💪 #fitness #healthylifestyle',
    image: 'https://th.bing.com/th/id/OIG.1gKgC0aJIo8sLYOQS7Ck?pid=ImgGn',
    numberOfComments: 2,
    numberOfRetweets: 5,
    numberOfLikes: 25,
    impressions: 500,
  },
  {
    id: '222222222',
    createdAt: '2023-04-27T19:45:00.000Z',
    user: {
      id: '987654321',
      name: 'Zuck',
      username: 'zuck',
      image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/zuck.jpeg',
    },
    content: 'Had an amazing surf session this morning',
    image: 'https://th.bing.com/th/id/OIG.bWlW3863P5mQ55u5B55o?pid=ImgGn',
    numberOfComments: 10,
    numberOfRetweets: 20,
    numberOfLikes: 100,
    impressions: 1000,
  },
  {
    id: '333333333',
    createdAt: '2023-04-26T12:00:00.000Z',
    user: {
      id: '123456789',
      name: 'Jane Smith',
      username: 'janesmith',
      image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/6.png',
    },
    content:
      'Excited to announce that I will be speaking at the upcoming tech conference in San Francisco! 🎉 #womenintech',
    numberOfComments: 5,
    numberOfRetweets: 10,
    numberOfLikes: 50,
    impressions: 1000,
  },
  {
    id: 't1',
    user: {
      id: 'u1',
      username: 'VadimNotJustDev',
      name: 'Vadim',
      image: 'https://github.com/silvaneimartins.png',
    },
    createdAt: '2020-08-27T12:00:00.000Z',
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    image: 'https://th.bing.com/th/id/OIG.7b64wykdLwJt_rs1ELjP?pid=ImgGn',
    numberOfComments: 123,
    numberOfRetweets: 11,
    numberOfLikes: 10,
  },
  {
    id: 't2',
    user: {
      id: 'u1',
      username: 'VadimNotJustDev',
      name: 'Vadim',
      image: 'https://github.com/silvaneimartins.png',
    },
    createdAt: '2020-08-27T12:00:00.000Z',
    content:
      "Hey Hey Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    numberOfComments: 4,
    numberOfRetweets: 11,
    numberOfLikes: 99,
  },
  {
    id: 't3',
    user: {
      id: 'u1',
      username: 'VadimNotJustDev',
      name: 'Vadim',
      image: 'https://github.com/silvaneimartins.png',
    },
    createdAt: '2020-08-27T12:00:00.000Z',
    content: 'Hello World',
    numberOfComments: 4,
    numberOfRetweets: 11,
    numberOfLikes: 99,
  },
  {
    id: 't4',
    user: {
      id: 'u1',
      username: 'VadimNotJustDev',
      name: 'Vadim',
      image: 'https://github.com/silvaneimartins.png',
    },
    createdAt: '2020-08-27T12:00:00.000Z',
    content:
      "Hey Hey Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    numberOfComments: 4,
    numberOfRetweets: 11,
    numberOfLikes: 99,
  },
];

export default tweets;
